// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/stats/v1alpha1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	rest "k8s.io/client-go/rest"
)

// NodeIPLatencyStatsGetter has a method to return a NodeIPLatencyStatInterface.
// A group's client should implement this interface.
type NodeIPLatencyStatsGetter interface {
	NodeIPLatencyStats() NodeIPLatencyStatInterface
}

// NodeIPLatencyStatInterface has methods to work with NodeIPLatencyStat resources.
type NodeIPLatencyStatInterface interface {
	Create(ctx context.Context, nodeIPLatencyStat *v1alpha1.NodeIPLatencyStat, opts v1.CreateOptions) (*v1alpha1.NodeIPLatencyStat, error)
	NodeIPLatencyStatExpansion
}

// nodeIPLatencyStats implements NodeIPLatencyStatInterface
type nodeIPLatencyStats struct {
	client rest.Interface
}

// newNodeIPLatencyStats returns a NodeIPLatencyStats
func newNodeIPLatencyStats(c *StatsV1alpha1Client) *nodeIPLatencyStats {
	return &nodeIPLatencyStats{
		client: c.RESTClient(),
	}
}

// Create takes the representation of a nodeIPLatencyStat and creates it.  Returns the server's representation of the nodeIPLatencyStat, and an error, if there is any.
func (c *nodeIPLatencyStats) Create(ctx context.Context, nodeIPLatencyStat *v1alpha1.NodeIPLatencyStat, opts v1.CreateOptions) (result *v1alpha1.NodeIPLatencyStat, err error) {
	result = &v1alpha1.NodeIPLatencyStat{}
	err = c.client.Post().
		Resource("nodeiplatencystats").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeIPLatencyStat).
		Do(ctx).
		Into(result)
	return
}
